### ISSUE TITLE
Render checklist syntax

### ISSUE THREAD

**Issue by thenanyu** [MacDownApp/macdown#10]
Reference: https://github.com/blog/1375-task-lists-in-gfm-issues-pulls-comments
I write a lot of todo lists in my markdown documents, it would be nice to render the github task list syntax in a nice way.

```
Example List
- [ ] unchecked item
- [x] checked item
```

There are a couple of hoedown extensions that do this, example:
https://github.com/kjdev/hoextdown

**Comment by andreac82** [comment]
I tried the standard syntax for checklists, which is:

```
- [ ] Checklist item 1
- [x] Checklist item 2
```

and it doesn't seem to be rendered, even if this issue is marked as completed. Perhaps Macdown has its own syntax to render this?

My Macdown version is `Version 0.7.2 (1008)` and it was installed very recently via Homebrew under Sequioia.
Homebrew still says the currently installed version is the latest.
