### ISSUE TITLE
[Question] What html engine does macdown use? Why the same color looks different from browser?

### ISSUE THREAD

**Issue by sgon00** [MacDownApp/macdown#1037]
What html engine does macdown use? Why the same color looks different from safari and chrome browsers? Can I let macdown use either `safari` or `chrome` to render the HTML page? Thanks a lot.

**Comment by sgon00** [comment]
I spent a day trying to solve this problem before opening this issue question, But after 10 minutes of opening this question, I finally solved it. This is nothing related to html render engine. I just need to add `-webkit-font-smoothing: antialiased;` to `body` in css file. Everything looks the same now. Closing the comment.

**Comment by uranusjr** [comment]
Technical detail: MacDown uses a variant of WebKit, similar to Safari’s. Why it appears different is likely because Safari recently changed the default font smoothing CSS. Honestly I don’t like the new style at all (it’s blurry like hell), but fortunately it’s easy enough to change it if you like it that way :D

**Comment by uranusjr** [comment]
(Title modified to improve discovery for future visitors.)
