### ISSUE TITLE
Add Macdown to Quick Look for .md files preview

### ISSUE THREAD

**Issue by Morane** [MacDownApp/macdown#1178]
On my brand new Mac, Quick Look doesn’t support .md files. That is, they are not previewed in Macdown. On my previuos Mac, I had both Macdown and Texts installed, and Quick Look used Texts to preview .md files. But I no longer want to have Texts installed. Is there a tip to add Macdown to Quick Look ?

**Comment by FelixFrey** [comment]
There is a QuickLook Plugin for this: [https://github.com/toland/qlmarkdown](https://github.com/toland/qlmarkdown)

**Comment by Morane** [comment]
Hi Felix,

Thanks for your message. How can I get this Plugin ? Is this simply a work in progress ?

**Comment by Morane** [comment]
Oops ! I see.

**Comment by relikd** [comment]
Hey there, I'd like to come back to this topic since the mentioned plugin seems not to be maintained anymore https://github.com/toland/qlmarkdown/issues/102. I think it would be nice if a MD QL plugin would be integrated in the app. Especially, because the md parser is already there, you would only need to have a QL wrapper plugin. The implementation would take some time but there should be no maintenance costs after that.
Just my 2c :)

**Comment by Morane** [comment]
Hi,

I agree. I saved this plug-in !

Best
