### ISSUE TITLE
Nested list not indenting

### ISSUE THREAD

**Issue by sgarrity** [MacDownApp/macdown#148]
With the following markdown, I'm not seeing the 2nd-level indenting on the 3rd list item:

``` markdown
* Lorem Ipsum
  * Lorem Ipsum
    * Lorem Ipsum
  * Lorem Ipsum
```

I expect the 3rd list item should be indented another level.

![screenshot 2014-09-03 19 56 04](https://cloud.githubusercontent.com/assets/58062/4142697/86b94cc4-33bd-11e4-8836-14b648b0c0c8.png)

**Comment by ffxsam** [comment]
I don't know if it's appropriate that someone decides 4 spaces is better than 2. Markdown is a standard, and 2 spaces is the convention for indented lists.

https://guides.github.com/features/mastering-markdown/

I'd really like to see this changed in MacDown.

**Comment by uranusjr** [comment]
Well, truth is, Markdown is really *not* a standard, but really just a set of conventions made up by John Gruber, and improvised upon which by many others.

It’s only normal for implementations to make their own decisions. If you don’t like the decision, you can always develop your own Markdown parser (which is what Hoedown, CommonMark, and others does), and if your parser is better than the current one, MacDown can then make the switch to use it. This is how open source software works.

**Comment by ffxsam** [comment]
[This parser](https://www.npmjs.com/package/marked) is one I see used everywhere. 63k downloads in just the past day! Sure enough, it handles multi-indented lists (with two spaces) without issue.

Of course, ultimately the decision is up to you guys. Just thought I'd point it out as I've had troubles with this, editing README files on GitHub projects.

**Comment by mstratman** [comment]
I just want to share an opinion of one that this is an incredibly important behavior for a markdown renderer.  Nested lists are extremely common in markdown.

You can certainly argue a literal  and semantic interpretation of a spec ("up to" 4 spaces) and you might be literally and semantically right.
But actual human beings aren't semantically following a markdown spec.

They are intuitively expecting this to be 3 levels.
```
* a
  *b
    *c
```

Survey 100 people and I suspect 100 will agree.

This is a deal-breaking bug.  Obviously I'm not paying you for this software, and  I assume most people aren't, so take it for what it's worth.  But I assume you do this because you want to share an awesome, valuable tool... and if that's the case, ask some of your users.   I'd be very, very, very, very, very surprised if anyone _wants or appreciates_ its current behavior.

**Comment by FranklinYu** [comment]
@mstratman We are not going to implement this feature alone, but if you can help finding a proper CommonMark implementation, your problem is automatically solved. Please see https://github.com/MacDownApp/macdown/issues/704#issuecomment-271089645.

**Comment by ffxsam** [comment]
@mstratman FWIW, I've been using Visual Studio Code for editing Markdown files. Its MD preview feature is rock solid, not to mention VS Code is an overall amazing editor.
