### ISSUE TITLE
miss Dependency prism

### ISSUE THREAD

**Issue by limbo0312** [MacDownApp/macdown#163]
cp: /Users/EGS/Desktop/macdown-master/Dependency/prism/components: No such file or directory
cp: /Users/EGS/Desktop/macdown-master/Dependency/prism/themes: No such file or directory
cp: /Users/EGS/Desktop/macdown-master/Dependency/prism/components.js: No such file or directory

build not success, why ?

**Comment by iDevSpread** [comment]
I have the same issue. What I have done is as the README.md tells. But the issues are there:
cp: Learning/GitHub/MarkDown-for-iPad/macdown/Dependency/prism/components: No such file or directory
cp: Learning/GitHub/MarkDown-for-iPad/macdown/Dependency/prism/themes: No such file or directory
cp: Learning/GitHub/MarkDown-for-iPad/macdown/Dependency/prism/plugins: No such file or directory
cp: Learning/GitHub/MarkDown-for-iPad/macdown/Dependency/prism/components.js: No such file or directory

**Comment by uranusjr** [comment]
Do you have `macdown/Dependency/prism`? What happens if you `cd` into it and run `git status`?

**Comment by iDevSpread** [comment]
Hi, Tzu-ping Chung,

I have solved this problem by the following means to fix my mistakes.

   - Do not set the project folders into the iCloud Drive. Some system
   modifications are not permitted through the iCloud folder.
   - Do not name the folder with a space, such as *iOS Development *which
   contains a space character in the name of this folder.

These are the two problems I met.

-- 
Elon
an iOS developer, reading lover, nature lover


On June 8, 2016 at 12:23:32 PM, Tzu-ping Chung (notifications@github.com)
wrote:

Do you have macdown/Dependency/prism? What happens if you cd into it and
run git status?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/MacDownApp/macdown/issues/163#issuecomment-224614881>,
or mute the thread
<https://github.com/notifications/unsubscribe/AKSV3cQC1zhoXZRMtoo6huGlkYglGRWRks5qJtdqgaJpZM4CiaDI>
.

**Comment by uranusjr** [comment]
Cool! The space in the path thing seems like a bug in the build script, but I guess we can put this behind now. :)
