### ISSUE TITLE
Don't prompt to save empty new file

### ISSUE THREAD

**Issue by xunlao** [MacDownApp/macdown#671]
COMMAND+Q with a blank markdown will prompts 'do you want to save' -- in

it's **empty**, why do I want to save it? 

Can you disable this feature? It hurt me every time I tried to logout my Mac.

And I have to OPTION+ESC to force quick MacDown..

Other than that it's a great app..

Any suggestion on fixing this?

**Comment by Jmuccigr** [comment]
That only happens for me if I've entered and then deleted text, so that the document is in a changed state. I agree though that if a file is **empty and unsaved**, MD shouldn't worry about it.

**Comment by xunlao** [comment]
@Jmuccigr you are right - maybe I was hoping that it can act like Sublime Text 3 where entered & deleted is considered empty

**Comment by franklinyu** [comment]
If you enter and delete the text, it thinks the document is changed; if you enter some text and undo it, it correctly regards the document as unchanged. This behavior is consistent with [TextEdit](https://en.wikipedia.org/wiki/TextEdit). As far as I understand, you are suggesting that MacDown should detect whether the new file is empty, and should not prompt to save in such case. Correct me if I am wrong.

**Comment by xunlao** [comment]
@franklinyu yes, that's textedit (and I don't think I like textedit)

Thanks for clarification!

**Comment by franklinyu** [comment]
I didn't mean that it is a good way; I meant it is probably the default way (so blame Apple for that 😄 ).

**Comment by xunlao** [comment]
And that's (maybe) causing the problem and it dies when I log out; I should open a new thread

**Comment by Jmuccigr** [comment]
FWIW, the latest version of BBEdit behaves in the OP's desired way: if the doc is empty, whether by deletion or undo-ing, it just closes the window without asking.

**Comment by uranusjr** [comment]
Just to clarify: Should this happen only for unsaved empty files? Or should it work with all empty files? Or should MacDown show a file as unmodified whenever a file has the same content as when it was last saved?

This distinction is important because a file can be saved in an iCloud drive, and needs to take concurrent editing in consideration. The current (system default) behaviour is the most naïve and safest: If you do anything, the document needs syncing. It is also quite straightforward to just discard all unsaved blank documents. The latter two would be much more involved.

**Comment by xunlao** [comment]
IMO the first one would be fine!

**Comment by Jmuccigr** [comment]
> Should this happen only for unsaved empty files?

This would be fine by me.

**Comment by franklinyu** [comment]
FWIW, Sublime Text 3 only did the first, i.e. only for unsaved (new) empty files.
