### ISSUE TITLE
Feature: autosave functionality

### ISSUE THREAD

**Issue by mklaber** [MacDownApp/macdown#70]
It'd be neat if MacDown had some sort of autosave functionality. Something similar to [TextMate](http://wiki.macromates.com/Main/Howtos#TimedAutoSave) or, dare I say it, [Visual Studio](http://msdn.microsoft.com/en-us/library/208c6tcy.aspx). It'd be helpful in situations like issue #69

**Comment by aalasolutions** [comment]
I came here today to know about this "AUTOSAVE" feature. I am trying to write something for leanpub and they ask you to add <<(code file) to include a file. Now MacDown is not supporting this feature. Marked 2 is only previewer and can show these files as well. 

So now I have disabled the preview pan on MacDown and it is not automatically updating the marked, i have to hit save each time.

Either add some other options for advance or add an autosave checkbox which just save the file when we hit anykey.

**Comment by uranusjr** [comment]
@aalasolutions “Autosave” may mean one of the two things:

1. Automatically performing a “Save” operation (what happens when you press cmd-S) on a file.
2. The “Autosave” feature on OS X. This feature keeps track of your unsaved modifications on a file, and backup the content somewhere else for you, mainly to prevent loss of work due to software and/or hardware failure.

The above discussion focuses on the second meaning. But in order for Marked 2 (or any application, really) to detect file changes, *the* file needs to actually change—backups don’t count—so you need autosave as in the first case, i.e. “save files automatically”. MacDown does not do that, so you need to do cmd-S manually to see the changes in Marked 2.

Supporting both kinds of auto-saving would be difficult, so the exact feature you want might not be available, unfortunately. But automatically saving a file periodically can be done by application-scripting. MacDown does not support that yet either (#324), but that’s a thing to keep an eye on.

**Comment by aalasolutions** [comment]
@uranusjr Thank you for detailed reply, Lets look into from other prospective, i went to Marked 2 as it have better preview for external changes and also more support for displaying content, this might not be standard for Markdown but that is requirement. 

For example using `<<(folder/file.ext)` will include the contents of the file in the preview, and that was the reason I used Marked

**Comment by uranusjr** [comment]
The include syntax is indeed a nice add-on. I will look into making this happen. :)

**Comment by aalasolutions** [comment]
Thank you

http://markua.com/
http://marked2app.com/help/Special_Syntax.html
http://marked2app.com/help/Multi-File_Documents.html

**Comment by thefonso** [comment]
Where is autosave now? I do not see it in Mojave. Why was this ever a thing. Save on focus lost is the most natural way to save a document in regular workflow which is why it exist in other text editors and IDE's. (sigh)

**Comment by FranklinYu** [comment]
@thefonso It has been there for a long time, and there’s nothing in Mojave that should break this behavior. Please be specific.
