### ISSUE TITLE
Associate with .md files

### ISSUE THREAD

**Issue by grosch** [MacDownApp/macdown#715]
Can you  associate .md files with macdown so that if I double-click on one your app opens instead of XCode?  I think Xcode is probably overwriting your association every time I upgrade.

**Comment by Jmuccigr** [comment]
You can. Do get-info on a .md file via cmd-I or right-click and then under "Open with" choose MacDown and click the "Change all…" button right underneath it.

I don't know whether XCode will blow this away, but it doesn't for me.

**Comment by franklinyu** [comment]
1. Cannot reproduce on El Capitan. Have just updated my Xcode to 8.2.1, and the filetype association remains.
2. Even if the association is broken by XCode in your Mac, it's probably a [Finder](https://support.apple.com/en-us/HT201732)/XCode bug, not specific to MacDown. You may want to try associating `.md` file with another application (like [Sublime Text](https://www.sublimetext.com/) or [Atom](https://atom.io/)) before next time you update XCode, and see if the association is still overwritten. If it is, then we probably can't do anything about it. Note that doing this with [TextEdit](https://en.wikipedia.org/wiki/TextEdit) is not very convincing because applications from Apple (like TextEdit and XCode) seems to have higher priority over third-party applications like Sublime Text and Atom.

Without further information, I tend to believe this is a Finder bug. I had some bug about finder before (not showing the correct icon even after I associate the file with MacDown).

**Comment by grosch** [comment]
I have the same issue about it being associated but not showing the icon.

**Comment by franklinyu** [comment]
That icon bug is a long-living one, too. See [this comment](http://superuser.com/questions/178316/how-to-set-an-icon-for-a-file-type-on-mac/225534#comment1387602_225534), for example.

**Comment by uranusjr** [comment]
Even I can’t change .md icons on my own machine properly, and I don’t have a damned idea how to fix it. Apple. ¯\_(ツ)_/¯
