### ISSUE TITLE
Divider should be hidden when preview/editor is completely out of sight

### ISSUE THREAD

**Issue by eunjae-lee** [MacDownApp/macdown#76]
![2014-07-20 11 45 48](https://cloud.githubusercontent.com/assets/499898/3637755/a96d0ae0-101c-11e4-98fd-4c52ececc35f.png)

Here's a screenshot with preview pane hidden. At the right side of this window, there's 1 pixel vertical line with white color. Can you remove this? It's kind of annoying to me :(

**Comment by jsuder** [comment]
Hi,

I've seen something about fixing dividers a few times in the changelogs, but it seems the main issue I have is still there. The issue is that... I see two scrollbars, either next to each other or on both sides, which simply looks ridiculous:

![screen shot 2015-02-12 at 23 14 30](https://cloud.githubusercontent.com/assets/28465/6178221/23729d9e-b30d-11e4-8062-5e07cadc88cf.png)
![screen shot 2015-02-12 at 23 14 34](https://cloud.githubusercontent.com/assets/28465/6178224/2868fdca-b30d-11e4-8fad-59cba1c69da6.png)

Is this something you're planning to fix?

**Comment by aaronraimist** [comment]
Are you dragging it all the way to the edge of the screen to hide it or using the menu item under View?

**Comment by jsuder** [comment]
Usually with the menu item or shortcut.

**Comment by uranusjr** [comment]
I seem to recall this behaviour from somewhere, but can’t remember the details. Could you share your hardware setup? What kind of Mac do you use? Do you use any peripherals (external keyboard, mouse, etc.)?

**Comment by jsuder** [comment]
On a iMac w/ Bluetooth keyboard and mouse and on a MacBook Air. Both have "Show scroll bars = Always" set in the System Preferences, because I don't like it when I can't see the position/length of text when I'm not scrolling.

**Comment by uranusjr** [comment]
The scrollbars are probably the problem, then. That system config was never taken into consideration, so it’s very possible I screwed up some size calculations. Could you re-post this into a new issue (with a link back to this thread)? It can be better tracked this way.
