### ISSUE TITLE
add ability to import html

### ISSUE THREAD

**Issue by domilgo** [MacDownApp/macdown#787]
How difficult would be a feature to import html and convert it to markdown?

**Comment by franklinyu** [comment]
Very difficult; I'm open to discussions/solutions, but I won't try to implement that myself. I don't even think that people agree about the desired behavior.

**Comment by uranusjr** [comment]
This really depends on whether you want strict conversion, or just want to convert simple constructs. There’s no way to guarantee perfect translation, but there’s actually markdownplease.com that does kind of sort of what you want. It is based on [html2text.py](http://www.aaronsw.com/2002/html2text/).

**Comment by franklinyu** [comment]
Note that in `html2text`, table (`<table>`) is ignored by design (see test [input](https://github.com/Alir3z4/html2text/blob/2016.9.19/test/table_ignore.html) and [output](https://github.com/Alir3z4/html2text/blob/2016.9.19/test/table_ignore.md)). In addition, [the original work](https://github.com/aaronsw/html2text) stopped in 2012; the one on PyPI is [one](https://github.com/Alir3z4/html2text) of the forks.

**Comment by domilgo** [comment]
Thanks for your comments and for the link. I've created a script to do the conversion. Thanks for your help!
