### ISSUE TITLE
Assembly code highlight support?

### ISSUE THREAD

**Issue by YikSanChan** [MacDownApp/macdown#818]
Is there any way to highlight assembly code in MacDown?

Thanks!

**Comment by franklinyu** [comment]
1. Is it some specific assembly like x86 or MIPS, or just general assembly?
2. Try [Netwide Assembler](https://en.wikipedia.org/wiki/Netwide_Assembler) (`nasm`).

**Comment by YikSanChan** [comment]
It is x86. For example,
![image](https://user-images.githubusercontent.com/17229109/26999878-cd93b492-4d58-11e7-8e87-a3c159ec7357.png)

**Comment by YikSanChan** [comment]
Great! nasm works.

**Comment by YikSanChan** [comment]
Is there any other way? Thx! (out of curiosity)

**Comment by franklinyu** [comment]
What do you mean by "other way"?

1. If you mean [other way to syntax highlight a block code instead of specifying the syntax in [info string](http://spec.commonmark.org/0.27/#info-string)], then no, there's no other way. Info string is *the* way to specify the syntax of a code block.
2. If you mean [directly use `x86` instead of `nasm`], then you can add the syntax alias as specified in https://github.com/MacDownApp/macdown/issues/682#issuecomment-256543487. However I don't think `x86` would be supported by any other tool or website.

**Comment by YikSanChan** [comment]
Thank you. Solved.
