### ISSUE TITLE
TypeScript code style support

### ISSUE THREAD

**Issue by Hongbo-Miao** [MacDownApp/macdown#827]
First thank you. MacDown is awesome!

Right now, it supports `javascript` and `js` well.
Please also supports `typescript` and `ts` well. Thanks!

![image](https://user-images.githubusercontent.com/3375461/27891675-f9d64b58-61af-11e7-994b-2077cb1c3433.png)

**Comment by franklinyu** [comment]
`typescript` is supported.

**Comment by Hongbo-Miao** [comment]
@franklinyu thanks, just tried, it works!

If can further support `ts`, that will be great!

It can help save some typing time and also provide consistent experience with GitHub like
`javascript` & `js`
`bash` & `sh`

**Comment by franklinyu** [comment]
GitHub tends to support as much as possible, because it has code from the world. `ts` is not as popular (thus not as portable) as `typescript`, so it is unlikely to be added into MacDown in future. However, if you really like it, you can add custom language alias as mentioned in https://github.com/MacDownApp/macdown/issues/682#issuecomment-256543487.

**Comment by Hongbo-Miao** [comment]
I understand. The thing there are hundred of thousands of existing files using `ts` now. I cannot update all docs.
Ok, I will find another markdown tool to introduce to our teams.

**Comment by Hongbo-Miao** [comment]
I understand. The thing is that there are hundreds of thousands of existing files using `ts` now. I cannot update all docs.
But thanks, I will find another markdown tool to introduce to our teams.
