### ISSUE TITLE
missing keyboard shortcuts ( underline, highlight)

### ISSUE THREAD

**Issue by jeanfabre** [MacDownApp/macdown#857]
Hi,

 Would it be possible to add the underline and highlight key board shortcuts? Currently using BetterTouchBar and I can't plug these two function because they lack keyboard shortcuts :)

 Bye,

 Jean

**Comment by uranusjr** [comment]
Sure! I didn’t add them simply because I don’t use them, and nobody seemed to care (until now). I’m not very keen to implement something I don’t use, but anyone interested can submit a PR and I’ll merge.

The tricky parts are likely be to come up with appropriate shortcuts, and disable them when they are disabled in the preferences.

**Comment by jeanfabre** [comment]
Hi

 I think this can be dismissed, because I wanted to add TouchBar supports, but I found out it;s apparently available... only I am struggling to find out to enable it.

 bye,

Jean

**Comment by franklinyu** [comment]
Closing this assuming that TouchBar is preferred. Will reopen if anyone wants this shortcut *in addition to* TouchBar.
