### ISSUE TITLE
Capitalizing image extension rotates the image

### ISSUE THREAD

**Issue by justinplasmeier** [MacDownApp/macdown#866]
I noticed this when embedding an image downloaded from my iPhone. The extension was capitalized (`photo.JPG`) so I capitalized it in MacDown as well. The result is that the image is rotated 90 degrees CCW. When I lowercased the letters to `photo.jpg`, the image returned to its correct position. 

![screen shot 2017-10-03 at 11 45 27 pm](https://user-images.githubusercontent.com/12720806/31159634-6eb345dc-a898-11e7-9639-96d81593b15d.png)
![screen shot 2017-10-03 at 11 45 38 pm](https://user-images.githubusercontent.com/12720806/31159637-7123ea06-a898-11e7-89b9-80472870fa6d.png)

**Comment by franklinyu** [comment]
Does not happen on my machine. Does it work for every file? With every extension?

**Comment by justinplasmeier** [comment]
Tried a .png file, no issue. Tried another jpg (downloaded from the web), no issue.

I guess this must be a weird iPhone/Mac corner case and likely not an issue with MacDown?

**Comment by uranusjr** [comment]
I think I know what the problem is. I vaguely remember there’s something wrong with how iOS camera’s orientation parameter has trouble interpolating with other devices, and cannot be shown as portrait or upside-down. I forgot the exact details, but this seems to be one of the examples.

Unfortunately there’s nothing we can do here. The images are rendered directly by WebKit, and we have no control over it. And even if we do, there is no way to detect the faulty orientation. :(
