### ISSUE TITLE
Git Support

### ISSUE THREAD

**Issue by leon332157** [MacDownApp/macdown#913]
Could you please use any Python module or some other stuff to support git *commit, push*?
I'm using this as editor of README.me on Github. So it will be so much better to have git support!
😄

**Comment by leon332157** [comment]
Is this good?
https://github.com/libgit2/pygit2

**Comment by leon332157** [comment]
And also, if you want to, I could help to make git support, but I know nothing about Objective-C, only Python. So how to make this as a preference in the app?

**Comment by franklinyu** [comment]
I would argue that Git support, if any, belongs to plug-in instead of core application.

**Comment by leon332157** [comment]
Ok

**Comment by leon332157** [comment]
I believe most people will use GUI instead of command lines.

**Comment by leon332157** [comment]
I think what will be good is to add a plugin in the Macdown app to interact with the UNIX git core application.

**Comment by uranusjr** [comment]
I agree with @franklinyu. It is true people will use GUI instead of command lines, but there are already tons of super good Git GUI solutions for Mac. I’ve heard good words about Tower and GitKraken, and Fork is pretty good if you don’t want to pay people (full disclosure: I don’t use any of them; all this is information from people around me). The commit and push operations has nothing to do with Markdown, and is thus out of scope of MacDown. But if you really are looking for something integrated, a plugin is the way to go (also I still don’t see how the plugin would be more convenient than standalone tools mentioned above).
