### ISSUE TITLE
Adding touch bar support

### ISSUE THREAD

**Issue by sitelight** [MacDownApp/macdown#969]
While contributing for another improvement, I have noticed the lack of Touch bar support, and came up with a very simple solution:
Integrating the main window toolbar buttons into a nice NSTouchBar object hooked into the SplitView editor.
[Pull request #970](https://github.com/MacDownApp/macdown/pull/970)
![img_7668](https://user-images.githubusercontent.com/8055061/39392780-5a280604-4abc-11e8-8507-7157c82eeec4.JPG)

**Comment by sitelight** [comment]
Hey @franklinyu I am struggling with the retina "@2x" feature, but I have done that in the meantime when I have noticed that there is no touch bar support for those of us that invested a huge deal of money into that great bar! :)

**Comment by franklinyu** [comment]
I mean we need to pick between #922 and your #970.

**Comment by sitelight** [comment]
That's a sure thing! @franklinyu I think that my version works better because there's only one file to modify, it WAY lighter! Frankly, I think that the other solution is too complicated, and use many third-party things... Moreover, I have used the exact icons already made for the main window toolbar, and same button layout, so no design choices here :) Make sure to use "Window" > "Show Touch bar" in Xcode to check what it's like with a "Touch bar enabled Macbook" (if you have not invested yet haha)

**Comment by alexkaessner** [comment]
@sitelight Hi, good to see that the Touch Bar finally made it‘s way to MacDown. As I already created Touch Bar optimized icons I would like to add them - because they already exist ans look better than the toolbar icons (in size and line width). Anyways, I can create a pull request and do this so you don’t have to do the work. 😉
**Is the Touch Bar layout customizable by it’s own or does your approach mirror the toolbar layout?**

PS: duplicate of #714
